add_newline = false
command_timeout = 1500

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
format = ' took [$duration]($style) '
min_time = 10000

[directory]
truncation_length = 5
format = "$path$lock_symbol "

[git_status]
conflicted = "âš”ï¸  "
ahead = "ğŸï¸ğŸ’¨Ã—${count} "
behind = "ğŸ¢Ã—${count} "
diverged = "ğŸ”±ğŸï¸ğŸ’¨Ã—${ahead_count} ğŸ¢Ã—${behind_count} "
untracked = "ğŸ›¤ï¸Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“Ã—${count} "
staged = "ğŸ—ƒï¸Ã—${count} "
renamed = "ğŸ“›Ã—${count} "
deleted = "ğŸ—‘ï¸Ã—${count} "
style = "bold white"
format = "$all_status$ahead_behind"

[git_state]
format = '($state( $progress_current of $progress_total)) '

[git_commit]
commit_hash_length = 8
style = "bold white"

[time]
disabled=false
format = '[$time]($style)'
